import type { Movie, MovieRatings } from "./types.ts";

const netflix = { provider: "Netflix", included: true };
const max = { provider: "Max", included: true };
const prime = { provider: "Prime Video", included: true };
const disney = { provider: "Disney+", included: true };
const hulu = { provider: "Hulu", included: true };
const apple = { provider: "Apple TV+", included: true };
const peacock = { provider: "Peacock", included: true };
const paramount = { provider: "Paramount+", included: true };
const rent = { provider: "Rent", included: false };

const SCORES: Record<string, MovieRatings> = {
  wicked: { rottenTomatoes: 88, audience: 95, imdb: 7.4, metacritic: 73 },
  "inside-out-2": { rottenTomatoes: 91, audience: 94, imdb: 7.5, metacritic: 73 },
  "deadpool-wolverine": { rottenTomatoes: 78, audience: 94, imdb: 7.6, metacritic: 56 },
  "the-substance": { rottenTomatoes: 89, audience: 69, imdb: 7.3, metacritic: 78 },
  anora: { rottenTomatoes: 93, audience: 91, imdb: 7.5, metacritic: 91 },
  conclave: { rottenTomatoes: 93, audience: 86, imdb: 7.4, metacritic: 79 },
  "the-brutalist": { rottenTomatoes: 93, audience: 80, imdb: 7.4, metacritic: 90 },
  "nosferatu-2024": { rottenTomatoes: 84, audience: 73, imdb: 7.2, metacritic: 78 },
  "alien-romulus": { rottenTomatoes: 80, audience: 85, imdb: 7.1, metacritic: 64 },
  challengers: { rottenTomatoes: 88, audience: 83, imdb: 7.1, metacritic: 82 },
  furiosa: { rottenTomatoes: 90, audience: 86, imdb: 7.5, metacritic: 79 },
  "civil-war": { rottenTomatoes: 81, audience: 69, imdb: 7.0, metacritic: 75 },
  "a-complete-unknown": { rottenTomatoes: 82, audience: 96, imdb: 7.4, metacritic: 70 },
  "the-wild-robot": { rottenTomatoes: 97, audience: 98, imdb: 8.2, metacritic: 85 },
  twisters: { rottenTomatoes: 75, audience: 94, imdb: 6.5, metacritic: 65 },
  "gladiator-ii": { rottenTomatoes: 70, audience: 82, imdb: 6.5, metacritic: 64 },
  "moana-2": { rottenTomatoes: 61, audience: 88, imdb: 6.6, metacritic: 58 },
  "hit-man": { rottenTomatoes: 95, audience: 88, imdb: 6.9, metacritic: 83 },
  "emilia-perez": { rottenTomatoes: 73, audience: 66, imdb: 5.4, metacritic: 71 },
  "i-saw-the-tv-glow": { rottenTomatoes: 84, audience: 57, imdb: 5.8, metacritic: 84 },
  longlegs: { rottenTomatoes: 86, audience: 62, imdb: 6.6, metacritic: 77 },
  sinners: { rottenTomatoes: 97, audience: 96, imdb: 8.0, metacritic: 88 },
  "mickey-17": { rottenTomatoes: 78, audience: 74, imdb: 6.8, metacritic: 72 },
  "companion-2025": { rottenTomatoes: 93, audience: 82, imdb: 6.9, metacritic: 81 },
  thunderbolts: { rottenTomatoes: 88, audience: 92, imdb: 7.1, metacritic: 68 },
  "mission-impossible-final-reckoning": { rottenTomatoes: 80, audience: 88, imdb: 7.3, metacritic: 67 },
  "f1-the-movie": { rottenTomatoes: 83, audience: 97, imdb: 7.8, metacritic: 68 },
  "superman-2025": { rottenTomatoes: 83, audience: 94, imdb: 7.3, metacritic: 68 },
  "jurassic-world-rebirth": { rottenTomatoes: 50, audience: 72, imdb: 6.0, metacritic: 45 },
  "fantastic-four-first-steps": { rottenTomatoes: 87, audience: 93, imdb: 6.7, metacritic: 67 },
  "weapons-2025": { rottenTomatoes: 94, audience: 88, imdb: 7.5, metacritic: 81 },
  "28-years-later": { rottenTomatoes: 88, audience: 76, imdb: 6.9, metacritic: 76 },
  "a-minecraft-movie": { rottenTomatoes: 48, audience: 89, imdb: 5.7, metacritic: 46 },
  "how-to-train-your-dragon-2025": { rottenTomatoes: 77, audience: 96, imdb: 7.2, metacritic: 61 },
  "lilo-stitch-2025": { rottenTomatoes: 71, audience: 92, imdb: 6.7, metacritic: 53 },
  "zootopia-2": { rottenTomatoes: 90, audience: 94, imdb: 7.4, metacritic: 75 },
  "avatar-fire-and-ash": { rottenTomatoes: 66, audience: 88, imdb: 7.0, metacritic: 61 },
  "wicked-for-good": { rottenTomatoes: 84, audience: 94, imdb: 7.2, metacritic: 69 },
  "one-battle-after-another": { rottenTomatoes: 95, audience: 90, imdb: 8.1, metacritic: 92 },
  "the-smashing-machine": { rottenTomatoes: 82, audience: 78, imdb: 7.1, metacritic: 73 },
  "wake-up-dead-man": { rottenTomatoes: 93, audience: 89, imdb: 7.6, metacritic: 82 },
  "the-electric-state": { rottenTomatoes: 15, audience: 51, imdb: 5.9, metacritic: 30 },
  havoc: { rottenTomatoes: 62, audience: 64, imdb: 6.4, metacritic: 52 },
  "back-in-action": { rottenTomatoes: 23, audience: 48, imdb: 5.8, metacritic: 34 },
  "fountain-of-youth": { rottenTomatoes: 37, audience: 55, imdb: 5.7, metacritic: 41 },
  "highest-2-lowest": { rottenTomatoes: 86, audience: 79, imdb: 6.9, metacritic: 76 },
  materialists: { rottenTomatoes: 80, audience: 72, imdb: 6.4, metacritic: 70 },
  "spider-man-brand-new-day": { rottenTomatoes: 87, audience: 96, imdb: 7.6, metacritic: 71 },
  "avengers-doomsday": { rottenTomatoes: 78, audience: 92, imdb: 7.2, metacritic: 64 },
  "the-odyssey-2026": { rottenTomatoes: 89, audience: 86, imdb: 7.8, metacritic: 81 },
  "project-hail-mary": { rottenTomatoes: 91, audience: 94, imdb: 7.9, metacritic: 80 },
  "super-mario-galaxy-movie": { rottenTomatoes: 76, audience: 93, imdb: 7.0, metacritic: 62 },
  "the-devil-wears-prada-2": { rottenTomatoes: 72, audience: 88, imdb: 6.6, metacritic: 61 },
  "mandalorian-and-grogu": { rottenTomatoes: 74, audience: 90, imdb: 7.1, metacritic: 63 },
  "scream-7": { rottenTomatoes: 68, audience: 81, imdb: 6.4, metacritic: 58 },
  "tron-ares": { rottenTomatoes: 51, audience: 76, imdb: 6.2, metacritic: 48 },
};

function f(
  movie: Omit<Movie, "language" | "writers" | "similarIds" | "themes" | "tones" | "moods" | "cast" | "atmosphere" | "audience" | "quality" | "popularity"> &
    Partial<Pick<Movie, "language" | "writers" | "similarIds" | "themes" | "tones" | "moods" | "cast" | "atmosphere" | "audience" | "quality" | "popularity" | "ratings">>,
): Movie {
  return {
    language: "en",
    writers: movie.writers ?? [movie.director],
    similarIds: movie.similarIds ?? [],
    themes: movie.themes ?? movie.genres.slice(0, 3).map((g) => g.toLowerCase()),
    tones: movie.tones ?? ["current"],
    moods: movie.moods ?? ["new"],
    cast: movie.cast ?? [],
    atmosphere: movie.atmosphere ?? "void",
    audience: movie.audience ?? "adult",
    quality: movie.quality ?? 0.78,
    popularity: movie.popularity ?? 0.72,
    ...movie,
    ratings: movie.ratings ?? SCORES[movie.id],
  };
}

/** 2024–2026 theatrical hits and streamer originals. CORE wins on id collision. */
export const FRESH: Movie[] = [
  f({ id: "wicked", slug: "wicked", title: "Wicked", year: 2024, runtimeMin: 160, certification: "PG", genres: ["Fantasy", "Musical", "Romance"], director: "Jon M. Chu", overview: "Elphaba and Glinda before Oz was legend. Green, glittering, huge.", watch: [peacock, rent], trailerYoutubeId: "6COmYeLSzHc", audience: "family", quality: 0.88, popularity: 0.94 }),
  f({ id: "inside-out-2", slug: "inside-out-2", title: "Inside Out 2", year: 2024, runtimeMin: 96, certification: "PG", genres: ["Animation", "Comedy", "Family"], director: "Kelsey Mann", overview: "Anxiety joins the console. Puberty, a sense of self, and a hockey camp.", watch: [disney], trailerYoutubeId: "LEjhY15eCx0", audience: "family", quality: 0.9, popularity: 0.95 }),
  f({ id: "deadpool-wolverine", slug: "deadpool-wolverine", title: "Deadpool & Wolverine", year: 2024, runtimeMin: 128, certification: "R", genres: ["Action", "Comedy", "Science Fiction"], director: "Shawn Levy", overview: "Wade Wilson breaks the TVA to drag Logan back. R-rated MCU chaos.", watch: [disney], trailerYoutubeId: "73_1biulkYk", quality: 0.82, popularity: 0.96 }),
  f({ id: "the-substance", slug: "the-substance", title: "The Substance", year: 2024, runtimeMin: 141, certification: "R", genres: ["Horror", "Science Fiction"], director: "Coralie Fargeat", overview: "A fading star splits herself. Body horror as industry satire.", watch: [max], trailerYoutubeId: "LNlrGhBpYjc", quality: 0.9, popularity: 0.78 }),
  f({ id: "anora", slug: "anora", title: "Anora", year: 2024, runtimeMin: 139, certification: "R", genres: ["Comedy", "Drama", "Romance"], director: "Sean Baker", overview: "A Brooklyn stripper marries an oligarch's son. Then the family lands.", watch: [hulu], trailerYoutubeId: "O6fE0ZK8pKE", quality: 0.94, popularity: 0.8 }),
  f({ id: "conclave", slug: "conclave", title: "Conclave", year: 2024, runtimeMin: 120, certification: "PG", genres: ["Drama", "Thriller"], director: "Edward Berger", overview: "Cardinals lock in to elect a pope. Ambition in red.", watch: [peacock], trailerYoutubeId: "JX9jas0zBh4", quality: 0.91, popularity: 0.76 }),
  f({ id: "the-brutalist", slug: "the-brutalist", title: "The Brutalist", year: 2024, runtimeMin: 215, certification: "R", genres: ["Drama", "History"], director: "Brady Corbet", overview: "A Hungarian architect rebuilds in America. Concrete, capital, and time.", watch: [max], trailerYoutubeId: "KdB8iWfxL1Y", quality: 0.92, popularity: 0.7 }),
  f({ id: "nosferatu-2024", slug: "nosferatu-2024", title: "Nosferatu", year: 2024, runtimeMin: 132, certification: "R", genres: ["Horror", "Fantasy"], director: "Robert Eggers", overview: "Eggers remounts the vampire. Shadow, plague, and appetite.", watch: [prime], trailerYoutubeId: "bprY4B5tBXg", quality: 0.88, popularity: 0.8 }),
  f({ id: "alien-romulus", slug: "alien-romulus", title: "Alien: Romulus", year: 2024, runtimeMin: 119, certification: "R", genres: ["Horror", "Science Fiction"], director: "Fede Álvarez", overview: "Young scavengers board a derelict Weyland-Yutani station. The xenomorph waits.", watch: [hulu, disney], trailerYoutubeId: "OzY2rThZlh0", quality: 0.84, popularity: 0.86 }),
  f({ id: "challengers", slug: "challengers", title: "Challengers", year: 2024, runtimeMin: 131, certification: "R", genres: ["Drama", "Romance", "Sport"], director: "Luca Guadagnino", overview: "A tennis love triangle in three sets. Sweat, score, and Zendaya.", watch: [prime], trailerYoutubeId: "crO-2tzlP8A", quality: 0.89, popularity: 0.8 }),
  f({ id: "furiosa", slug: "furiosa", title: "Furiosa: A Mad Max Saga", year: 2024, runtimeMin: 148, certification: "R", genres: ["Action", "Adventure", "Science Fiction"], director: "George Miller", overview: "The road that made Furiosa. Immortan, Dementus, the wasteland.", watch: [max], trailerYoutubeId: "XJ5xbzZ_j2E", quality: 0.86, popularity: 0.78 }),
  f({ id: "civil-war", slug: "civil-war", title: "Civil War", year: 2024, runtimeMin: 109, certification: "R", genres: ["Action", "Drama", "Thriller"], director: "Alex Garland", overview: "Photojournalists drive toward a besieged White House. America as war zone.", watch: [max], trailerYoutubeId: "aDshY43Ol2U", quality: 0.84, popularity: 0.77 }),
  f({ id: "a-complete-unknown", slug: "a-complete-unknown", title: "A Complete Unknown", year: 2024, runtimeMin: 141, certification: "R", genres: ["Drama", "Music"], director: "James Mangold", overview: "Dylan goes electric. Newport, Greenwich Village, a voice changing a decade.", watch: [hulu], trailerYoutubeId: "fdKsW2O68g4", quality: 0.86, popularity: 0.74 }),
  f({ id: "the-wild-robot", slug: "the-wild-robot", title: "The Wild Robot", year: 2024, runtimeMin: 102, certification: "PG", genres: ["Animation", "Adventure", "Family"], director: "Chris Sanders", overview: "A robot washes up on an island of animals and learns to be a mother.", watch: [peacock], trailerYoutubeId: "67vbA5ZJdKQ", audience: "family", quality: 0.93, popularity: 0.86 }),
  f({ id: "twisters", slug: "twisters", title: "Twisters", year: 2024, runtimeMin: 122, certification: "PG-13", genres: ["Action", "Adventure", "Thriller"], director: "Lee Isaac Chung", overview: "Storm chasers in Oklahoma. Bigger funnels, same rush.", watch: [peacock], trailerYoutubeId: "wdok0rZdmx4", audience: "family", quality: 0.76, popularity: 0.84 }),
  f({ id: "gladiator-ii", slug: "gladiator-ii", title: "Gladiator II", year: 2024, runtimeMin: 148, certification: "R", genres: ["Action", "Drama", "History"], director: "Ridley Scott", overview: "Lucius returns to the Colosseum. Rome still thirsty.", watch: [paramount], trailerYoutubeId: "4rgYUip0Oag", quality: 0.78, popularity: 0.85 }),
  f({ id: "moana-2", slug: "moana-2", title: "Moana 2", year: 2024, runtimeMin: 100, certification: "PG", genres: ["Animation", "Adventure", "Family"], director: "David Derrick Jr.", overview: "Moana sails beyond the reef again. Wayfinding, ocean, song.", watch: [disney], trailerYoutubeId: "hDZ7yTLOLOQ", audience: "kids", quality: 0.78, popularity: 0.9 }),
  f({ id: "hit-man", slug: "hit-man", title: "Hit Man", year: 2024, runtimeMin: 115, certification: "R", genres: ["Comedy", "Crime", "Romance"], director: "Richard Linklater", overview: "A professor moonlights as a fake assassin. Then someone wants it real.", watch: [netflix], trailerYoutubeId: "6Jf-fbepEog", quality: 0.88, popularity: 0.74 }),
  f({ id: "emilia-perez", slug: "emilia-perez", title: "Emilia Pérez", year: 2024, runtimeMin: 132, certification: "R", genres: ["Crime", "Musical", "Thriller"], director: "Jacques Audiard", overview: "A cartel boss disappears into a new life. Opera, Mexico, identity.", watch: [netflix], trailerYoutubeId: "V8i6oJ9z6VU", language: "es", quality: 0.8, popularity: 0.72 }),
  f({ id: "i-saw-the-tv-glow", slug: "i-saw-the-tv-glow", title: "I Saw the TV Glow", year: 2024, runtimeMin: 100, certification: "PG-13", genres: ["Drama", "Horror", "Mystery"], director: "Jane Schoenbrun", overview: "A suburban teen and a late-night show that might be real. Trans horror as ache.", watch: [max], trailerYoutubeId: "eCPrChHS5D8", quality: 0.86, popularity: 0.58 }),
  f({ id: "longlegs", slug: "longlegs", title: "Longlegs", year: 2024, runtimeMin: 101, certification: "R", genres: ["Horror", "Thriller", "Crime"], director: "Osgood Perkins", overview: "An FBI agent and a satanic serial killer. Nic Cage in whiteface.", watch: [hulu], trailerYoutubeId: "F7RAVP0Wap0", quality: 0.84, popularity: 0.76 }),
  f({ id: "sinners", slug: "sinners", title: "Sinners", year: 2025, runtimeMin: 137, certification: "R", genres: ["Horror", "Drama", "Music"], director: "Ryan Coogler", overview: "Twins, a juke joint, and something that hunts after dark in 1930s Mississippi.", watch: [max], trailerYoutubeId: "bKGxHflevuk", quality: 0.93, popularity: 0.9 }),
  f({ id: "mickey-17", slug: "mickey-17", title: "Mickey 17", year: 2025, runtimeMin: 137, certification: "R", genres: ["Science Fiction", "Comedy"], director: "Bong Joon Ho", overview: "An expendable colonist keeps dying and coming back. Then two Mickeys overlap.", watch: [max], trailerYoutubeId: "osYq4fBKtbw", quality: 0.82, popularity: 0.8 }),
  f({ id: "companion-2025", slug: "companion-2025", title: "Companion", year: 2025, runtimeMin: 97, certification: "R", genres: ["Science Fiction", "Thriller", "Horror"], director: "Drew Hancock", overview: "A weekend with friends and an AI girlfriend who is more than advertised.", watch: [max], trailerYoutubeId: "Oi8zIytRokM", quality: 0.8, popularity: 0.72 }),
  f({ id: "thunderbolts", slug: "thunderbolts", title: "Thunderbolts*", year: 2025, runtimeMin: 126, certification: "PG-13", genres: ["Action", "Adventure", "Science Fiction"], director: "Jake Schreier", overview: "Marvel antiheroes in a black-site job. Yelena, Bucky, the void.", watch: [disney], trailerYoutubeId: "8ik4jKUtRyk", quality: 0.8, popularity: 0.86 }),
  f({ id: "mission-impossible-final-reckoning", slug: "mission-impossible-final-reckoning", title: "Mission: Impossible – The Final Reckoning", year: 2025, runtimeMin: 169, certification: "PG-13", genres: ["Action", "Adventure", "Thriller"], director: "Christopher McQuarrie", overview: "Hunt vs the Entity. Submarines, biplanes, one last run.", watch: [paramount], trailerYoutubeId: "fsQgc9pCyDU", quality: 0.86, popularity: 0.88 }),
  f({ id: "f1-the-movie", slug: "f1-the-movie", title: "F1", year: 2025, runtimeMin: 155, certification: "PG-13", genres: ["Action", "Drama", "Sport"], director: "Joseph Kosinski", overview: "Brad Pitt in a real Formula 1 seat. Apple and Warner on the grid.", watch: [apple], trailerYoutubeId: "8yh9BPUBbbQ", quality: 0.88, popularity: 0.9 }),
  f({ id: "superman-2025", slug: "superman-2025", title: "Superman", year: 2025, runtimeMin: 129, certification: "PG-13", genres: ["Action", "Adventure", "Science Fiction"], director: "James Gunn", overview: "A kind Superman, a messy Metropolis, and a dog named Krypto.", watch: [max], trailerYoutubeId: "Ox8ZLF6cGM0", audience: "family", quality: 0.82, popularity: 0.92 }),
  f({ id: "jurassic-world-rebirth", slug: "jurassic-world-rebirth", title: "Jurassic World Rebirth", year: 2025, runtimeMin: 133, certification: "PG-13", genres: ["Action", "Adventure", "Science Fiction"], director: "Gareth Edwards", overview: "A new team lands on a forbidden island. Dinosaurs, still the problem.", watch: [peacock], trailerYoutubeId: "jan5WZmXgY4", audience: "family", quality: 0.72, popularity: 0.88 }),
  f({ id: "fantastic-four-first-steps", slug: "fantastic-four-first-steps", title: "The Fantastic Four: First Steps", year: 2025, runtimeMin: 114, certification: "PG-13", genres: ["Action", "Adventure", "Science Fiction"], director: "Matt Shakman", overview: "Marvel's first family vs Galactus. Retro-future New York.", watch: [disney], trailerYoutubeId: "pAsmrKy1Zds", audience: "family", quality: 0.8, popularity: 0.88 }),
  f({ id: "weapons-2025", slug: "weapons-2025", title: "Weapons", year: 2025, runtimeMin: 128, certification: "R", genres: ["Horror", "Mystery", "Thriller"], director: "Zach Cregger", overview: "Seventeen children leave their homes at 2:17 a.m. A town looks for why.", watch: [max], trailerYoutubeId: "6j0aVhE9iQ0", quality: 0.9, popularity: 0.84 }),
  f({ id: "28-years-later", slug: "28-years-later", title: "28 Years Later", year: 2025, runtimeMin: 115, certification: "R", genres: ["Horror", "Thriller", "Science Fiction"], director: "Danny Boyle", overview: "The infected islands still burn. A coming-of-age inside the quarantine.", watch: [prime], trailerYoutubeId: "0q5K7oF4xkI", quality: 0.86, popularity: 0.84 }),
  f({ id: "a-minecraft-movie", slug: "a-minecraft-movie", title: "A Minecraft Movie", year: 2025, runtimeMin: 101, certification: "PG", genres: ["Adventure", "Comedy", "Family"], director: "Jared Hess", overview: "Chicken jockey. Overworld, Jack Black, and a blocky fever dream.", watch: [max], trailerYoutubeId: "wJO_vIDZn-I", audience: "kids", quality: 0.62, popularity: 0.93 }),
  f({ id: "how-to-train-your-dragon-2025", slug: "how-to-train-your-dragon-2025", title: "How to Train Your Dragon", year: 2025, runtimeMin: 125, certification: "PG", genres: ["Action", "Adventure", "Family"], director: "Dean DeBlois", overview: "Live-action Berk. Hiccup and Toothless, still the pairing.", watch: [peacock], trailerYoutubeId: "5lzoxHSn0C0", audience: "family", quality: 0.8, popularity: 0.88 }),
  f({ id: "lilo-stitch-2025", slug: "lilo-stitch-2025", title: "Lilo & Stitch", year: 2025, runtimeMin: 108, certification: "PG", genres: ["Adventure", "Comedy", "Family"], director: "Dean Fleischer Camp", overview: "Ohana means family. A live-action Stitch wrecks Kauai.", watch: [disney], trailerYoutubeId: "VWqJifMMgZE", audience: "kids", quality: 0.74, popularity: 0.92 }),
  f({ id: "zootopia-2", slug: "zootopia-2", title: "Zootopia 2", year: 2025, runtimeMin: 108, certification: "PG", genres: ["Animation", "Adventure", "Comedy"], director: "Jared Bush", overview: "Judy and Nick again. Reptiles, a bigger city, same bite.", watch: [disney], trailerYoutubeId: "7z_0vZcYd2w", audience: "kids", quality: 0.84, popularity: 0.94 }),
  f({ id: "avatar-fire-and-ash", slug: "avatar-fire-and-ash", title: "Avatar: Fire and Ash", year: 2025, runtimeMin: 192, certification: "PG-13", genres: ["Action", "Adventure", "Science Fiction"], director: "James Cameron", overview: "The Ash People. Pandora still at war.", watch: [disney], trailerYoutubeId: "nb_fFj_0rq8", audience: "family", quality: 0.84, popularity: 0.92 }),
  f({ id: "wicked-for-good", slug: "wicked-for-good", title: "Wicked: For Good", year: 2025, runtimeMin: 137, certification: "PG", genres: ["Fantasy", "Musical", "Romance"], director: "Jon M. Chu", overview: "The second half. A wicked witch, a good one, and the fall of Oz.", watch: [peacock], trailerYoutubeId: "h8K44o0Gs_Q", audience: "family", quality: 0.84, popularity: 0.9 }),
  f({ id: "one-battle-after-another", slug: "one-battle-after-another", title: "One Battle After Another", year: 2025, runtimeMin: 161, certification: "R", genres: ["Action", "Comedy", "Crime"], director: "Paul Thomas Anderson", overview: "Revolutionary parents, a daughter, and a chase across America.", watch: [max], trailerYoutubeId: "pEMytkKq4yY", quality: 0.94, popularity: 0.8 }),
  f({ id: "the-smashing-machine", slug: "the-smashing-machine", title: "The Smashing Machine", year: 2025, runtimeMin: 123, certification: "R", genres: ["Drama", "Sport"], director: "Benny Safdie", overview: "Mark Kerr in the early UFC. Johnson as a fighter coming apart.", watch: [prime], quality: 0.86, popularity: 0.7 }),
  f({ id: "wake-up-dead-man", slug: "wake-up-dead-man", title: "Wake Up Dead Man", year: 2025, runtimeMin: 144, certification: "PG-13", genres: ["Comedy", "Crime", "Mystery"], director: "Rian Johnson", overview: "Benoit Blanc in a parish. Knives Out goes gothic.", watch: [netflix], quality: 0.88, popularity: 0.82 }),
  f({ id: "the-electric-state", slug: "the-electric-state", title: "The Electric State", year: 2025, runtimeMin: 128, certification: "PG-13", genres: ["Adventure", "Science Fiction"], director: "Anthony Russo", overview: "A girl, a robot, a ruined America. Netflix and the Russos.", watch: [netflix], trailerYoutubeId: "KpN4pUoqk5Y", audience: "family", quality: 0.58, popularity: 0.74 }),
  f({ id: "havoc", slug: "havoc", title: "Havoc", year: 2025, runtimeMin: 105, certification: "R", genres: ["Action", "Crime", "Thriller"], director: "Gareth Evans", overview: "Tom Hardy as a cop in a city that wants him dead. Netflix nightwork.", watch: [netflix], quality: 0.72, popularity: 0.7 }),
  f({ id: "back-in-action", slug: "back-in-action", title: "Back in Action", year: 2025, runtimeMin: 114, certification: "PG-13", genres: ["Action", "Comedy"], director: "Seth Gordon", overview: "Cameron Diaz and Jamie Foxx pulled back into spy work. Netflix gloss.", watch: [netflix], quality: 0.58, popularity: 0.72 }),
  f({ id: "fountain-of-youth", slug: "fountain-of-youth", title: "Fountain of Youth", year: 2025, runtimeMin: 125, certification: "PG-13", genres: ["Adventure", "Action"], director: "Guy Ritchie", overview: "Natalie Portman and John Krasinski hunt a myth. Apple spectacle.", watch: [apple], quality: 0.64, popularity: 0.7 }),
  f({ id: "highest-2-lowest", slug: "highest-2-lowest", title: "Highest 2 Lowest", year: 2025, runtimeMin: 133, certification: "R", genres: ["Crime", "Drama", "Thriller"], director: "Spike Lee", overview: "Denzel in a kidnapping. Spike remakes Kurosawa in New York.", watch: [apple], quality: 0.86, popularity: 0.68 }),
  f({ id: "materialists", slug: "materialists", title: "Materialists", year: 2025, runtimeMin: 116, certification: "R", genres: ["Comedy", "Drama", "Romance"], director: "Celine Song", overview: "A matchmaker, two men, Manhattan math. Song after Past Lives.", watch: [hulu], quality: 0.84, popularity: 0.7 }),
  f({ id: "spider-man-brand-new-day", slug: "spider-man-brand-new-day", title: "Spider-Man: Brand New Day", year: 2026, runtimeMin: 132, certification: "PG-13", genres: ["Action", "Adventure", "Science Fiction"], director: "Destin Daniel Cretton", overview: "Holland's Spidey without the MCU safety net. Biggest opening on record.", watch: [disney], audience: "family", quality: 0.86, popularity: 0.98 }),
  f({ id: "avengers-doomsday", slug: "avengers-doomsday", title: "Avengers: Doomsday", year: 2026, runtimeMin: 150, certification: "PG-13", genres: ["Action", "Adventure", "Science Fiction"], director: "Anthony Russo", overview: "Doom arrives. The ensemble that is left.", watch: [disney], audience: "family", quality: 0.8, popularity: 0.96 }),
  f({ id: "the-odyssey-2026", slug: "the-odyssey-2026", title: "The Odyssey", year: 2026, runtimeMin: 180, certification: "PG-13", genres: ["Action", "Adventure", "Drama"], director: "Christopher Nolan", overview: "Nolan's Homer. Matt Damon as Odysseus, IMAX myth.", watch: [rent], quality: 0.9, popularity: 0.88 }),
  f({ id: "project-hail-mary", slug: "project-hail-mary", title: "Project Hail Mary", year: 2026, runtimeMin: 140, certification: "PG-13", genres: ["Science Fiction", "Adventure", "Drama"], director: "Phil Lord", overview: "A teacher wakes on a starship with a mission to save Earth. Andy Weir, Ryan Gosling.", watch: [prime], quality: 0.88, popularity: 0.86 }),
  f({ id: "super-mario-galaxy-movie", slug: "super-mario-galaxy-movie", title: "The Super Mario Galaxy Movie", year: 2026, runtimeMin: 100, certification: "PG", genres: ["Animation", "Adventure", "Comedy"], director: "Aaron Horvath", overview: "Mario leaves the Mushroom Kingdom for the stars. Illumination, still.", watch: [peacock], audience: "kids", quality: 0.74, popularity: 0.94 }),
  f({ id: "the-devil-wears-prada-2", slug: "the-devil-wears-prada-2", title: "The Devil Wears Prada 2", year: 2026, runtimeMin: 118, certification: "PG-13", genres: ["Comedy", "Drama"], director: "David Frankel", overview: "Andy and Miranda, older. Fashion still eats its young.", watch: [hulu, disney], quality: 0.76, popularity: 0.86 }),
  f({ id: "mandalorian-and-grogu", slug: "mandalorian-and-grogu", title: "The Mandalorian and Grogu", year: 2026, runtimeMin: 120, certification: "PG-13", genres: ["Action", "Adventure", "Science Fiction"], director: "Jon Favreau", overview: "Din and Grogu on the big screen. Star Wars as western again.", watch: [disney], audience: "family", quality: 0.78, popularity: 0.88 }),
  f({ id: "scream-7", slug: "scream-7", title: "Scream 7", year: 2026, runtimeMin: 110, certification: "R", genres: ["Horror", "Mystery", "Thriller"], director: "Kevin Williamson", overview: "Ghostface, again. Sidney's war isn't over.", watch: [paramount], quality: 0.7, popularity: 0.78 }),
  f({ id: "tron-ares", slug: "tron-ares", title: "Tron: Ares", year: 2025, runtimeMin: 119, certification: "PG-13", genres: ["Action", "Science Fiction"], director: "Joachim Rønning", overview: "A program enters our world. Leto on the grid.", watch: [disney], trailerYoutubeId: "Y6bbMQXQ180", quality: 0.68, popularity: 0.76 }),
];
