/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AthandleRouteImport } from './routes/@$handle'
import { Route as AlgorithmRouteImport } from './routes/algorithm'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TonightRouteImport } from './routes/tonight'
import { Route as TuneRouteImport } from './routes/tune'
import { Route as ApiGrokStatusRouteImport } from './routes/api/grok-status'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as MovieSlugRouteImport } from './routes/movie.$slug'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AthandleRoute = AthandleRouteImport.update({
  id: '/@$handle',
  path: '/@$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmRoute = AlgorithmRouteImport.update({
  id: '/algorithm',
  path: '/algorithm',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TonightRoute = TonightRouteImport.update({
  id: '/tonight',
  path: '/tonight',
  getParentRoute: () => rootRouteImport,
} as any)
const TuneRoute = TuneRouteImport.update({
  id: '/tune',
  path: '/tune',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrokStatusRoute = ApiGrokStatusRouteImport.update({
  id: '/api/grok-status',
  path: '/api/grok-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/@$handle': typeof AthandleRoute
  '/algorithm': typeof AlgorithmRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tonight': typeof TonightRoute
  '/tune': typeof TuneRoute
  '/api/grok-status': typeof ApiGrokStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/@$handle': typeof AthandleRoute
  '/algorithm': typeof AlgorithmRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tonight': typeof TonightRoute
  '/tune': typeof TuneRoute
  '/api/grok-status': typeof ApiGrokStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/@$handle': typeof AthandleRoute
  '/algorithm': typeof AlgorithmRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/tonight': typeof TonightRoute
  '/tune': typeof TuneRoute
  '/api/grok-status': typeof ApiGrokStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/@$handle'
    | '/algorithm'
    | '/live'
    | '/login'
    | '/profile'
    | '/saved'
    | '/search'
    | '/tonight'
    | '/tune'
    | '/api/grok-status'
    | '/api/health'
    | '/movie/$slug'
    | '/u/$handle'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/@$handle'
    | '/algorithm'
    | '/live'
    | '/login'
    | '/profile'
    | '/saved'
    | '/search'
    | '/tonight'
    | '/tune'
    | '/api/grok-status'
    | '/api/health'
    | '/movie/$slug'
    | '/u/$handle'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/@$handle'
    | '/algorithm'
    | '/live'
    | '/login'
    | '/profile'
    | '/saved'
    | '/search'
    | '/tonight'
    | '/tune'
    | '/api/grok-status'
    | '/api/health'
    | '/movie/$slug'
    | '/u/$handle'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthandleRoute: typeof AthandleRoute
  AlgorithmRoute: typeof AlgorithmRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  TonightRoute: typeof TonightRoute
  TuneRoute: typeof TuneRoute
  ApiGrokStatusRoute: typeof ApiGrokStatusRoute
  ApiHealthRoute: typeof ApiHealthRoute
  MovieSlugRoute: typeof MovieSlugRoute
  UHandleRoute: typeof UHandleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@$handle': {
      id: '/@$handle'
      path: '/@$handle'
      fullPath: '/@$handle'
      preLoaderRoute: typeof AthandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithm': {
      id: '/algorithm'
      path: '/algorithm'
      fullPath: '/algorithm'
      preLoaderRoute: typeof AlgorithmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tonight': {
      id: '/tonight'
      path: '/tonight'
      fullPath: '/tonight'
      preLoaderRoute: typeof TonightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tune': {
      id: '/tune'
      path: '/tune'
      fullPath: '/tune'
      preLoaderRoute: typeof TuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grok-status': {
      id: '/api/grok-status'
      path: '/api/grok-status'
      fullPath: '/api/grok-status'
      preLoaderRoute: typeof ApiGrokStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthandleRoute: AthandleRoute,
  AlgorithmRoute: AlgorithmRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  TonightRoute: TonightRoute,
  TuneRoute: TuneRoute,
  ApiGrokStatusRoute: ApiGrokStatusRoute,
  ApiHealthRoute: ApiHealthRoute,
  MovieSlugRoute: MovieSlugRoute,
  UHandleRoute: UHandleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
